version: '3.8'

services:
  lightnin_classifier:
    build: .
    container_name: LightningClassifier
    shm_size: '4gb'
    volumes:
      - .:/app
    tty: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]