name: LINT

on:
  push:
  pull_request:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build --build-arg ENVIRONMENT=dev -t my-lint-container .

      - name: Run Linter in Container
        run: docker run --rm my-lint-container bash -c "pixi run -e dev lint"
